language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7

env:
  - DRUPAL_CORE=8.2.x
  - DRUPAL_CORE=8.3.x
  - DRUPAL_CORE=8.4.x

matrix:
  # Don't wait for the allowed failures to build.
  fast_finish: true
  include:
    - php: 7
      env:
        - DRUPAL_CORE=8.4.x
        # Only run code coverage on the latest php and drupal versions.
        - WITH_PHPDBG_COVERAGE=true
  allow_failures:
    # Allow the code coverage report to fail.
    - env: WITH_PHPDBG_COVERAGE=true DRUPAL_CORE=8.4.x

mysql:
  database: graphql
  username: root
  encoding: utf8

# Cache composer downloads because cloning Coder from drupal.org is very slow :-(
cache:
  directories:
    - $HOME/.composer

before_script:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini

  # Determine the php settings file location.
  - if [[ $TRAVIS_PHP_VERSION = hhvm* ]];
      then export PHPINI=/etc/hhvm/php.ini;
      else export PHPINI=$HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    fi

  # PHP Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated
  # and will be removed in a future version. To avoid this warning set
  # 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input
  # stream instead.
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]];
      then echo always_populate_raw_post_data = -1 >> $PHPINI;
    fi;

  # Disable the default memory limit.
  - echo memory_limit = -1 >> $PHPINI

  # Remember the current graphql test directory for later use in the Drupal
  # installation.
  - export TESTDIR=$(pwd)

  # Navigate out of module directory to prevent blown stack by recursive module
  # lookup.
  - cd ..

  # Create database.
  - mysql -e 'create database graphql'
  # Export database variable for kernel tests.
  - export SIMPLETEST_DB=mysql://root:@127.0.0.1/graphql
  # Download Drupal 8 core from the Github mirror because it is faster.
  - travis_retry git clone --branch $DRUPAL_CORE --depth 1 https://github.com/drupal/drupal.git
  - cd drupal

  # Reference the module in the build site.
  - ln -s $TESTDIR modules/graphql

  # Run composer install for Drupal 8.2. We need an up-to-date composer when
  # installing Drupal 8.2.
  - composer self-update
  # Bring in the module dependencies without requiring a merge plugin.
  - composer require youshido/graphql:~1.5
  # The require already triggered the install.

  # Start a web server on port 8888, run in the background.
  - php -S localhost:8888 &

  # Export web server URL for browser tests.
  - export SIMPLETEST_BASE_URL=http://localhost:8888

script:
  # Run the unit tests which also include the kernel tests. When running with
  # phpdbg we need to replace all code occurrences that check for 'cli' with
  # 'phpdbg'. Some files might be write protected, hence the '|| true'.
  - if [[ "$WITH_PHPDBG_COVERAGE" == "true" ]];
      then
        grep -rl 'cli' core modules | xargs sed -i "s/'cli'/'phpdbg'/g" || true;
        phpdbg -qrr vendor/bin/phpunit --configuration core/phpunit.xml.dist --coverage-clover modules/graphql/coverage.xml modules/graphql;
      else
        vendor/bin/phpunit --configuration core/phpunit.xml.dist modules/graphql;
    fi

after_success:
  - if [[ "$WITH_PHPDBG_COVERAGE" == "true" ]];
      then
        bash <(curl -s https://codecov.io/bash);
        wget https://scrutinizer-ci.com/ocular.phar;
        php ocular.phar code-coverage:upload --format=php-clover coverage.xml;
    fi
